### ISSUE TITLE
[FEAT] Add/incorporate Gitpod

### ISSUE THREAD

**Issue by Panquesito7** [srbhr/website-for-resume-matcher#12]
### Description

By adding the Gitpod Ready-to-code system, anyone can easily run the website in one single click without installing anything. This is very useful because not everyone has the required dependencies installed, and also makes it much faster to deploy and make contributions.

Let me know what you think about this. If you like it, I'd love to work on this. 🙂

**Comment by srbhr** [comment]
Hi @Panquesito7  I think so too, but I'm planning to change the website. Like maybe in the coming few months, change the landing page of this website to something else, using React, Next etc.

**Comment by srbhr** [comment]
Okay @Panquesito7 then do add that PR. I thought it'll be a big change.
