### ISSUE TITLE
Links opening in the same window

### ISSUE THREAD

**Issue by sandipkarmokar** [srbhr/website-for-resume-matcher#17]
Is it intentional that every link is opening the same window as the current site?

**Comment by srbhr** [comment]
Could be, need to check which link are you talking about?

**Comment by sandipkarmokar** [comment]
almost all the links, including footer links, navbar links and even the contribute link

**Comment by sandipkarmokar** [comment]
@srbhr  any update?

**Comment by millette** [comment]
PR available: #18
